#!/bin/bash

# Atualiza a lista de pacotes
apt update

# Instala o Apache2
apt install -y apache2

# Inicia o Apache2
systemctl start apache2

# Habilita o Apache2 para iniciar na inicialização do sistema
systemctl enable apache2

# Exibe uma mensagem indicando que a instalação foi concluída com êxito
echo "O Apache2 foi instalado."
