#!/bin/bash

# Atualiza a lista de pacotes
sudo apt-get update

# Instala dependências necessárias
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

# Adiciona a chave GPG oficial do Docker
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

# Adiciona o repositório do Docker
echo "deb [signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

# Atualiza novamente a lista de pacotes após adicionar o repositório
sudo apt-get update

# Instala o Docker
sudo apt-get install -y docker-ce docker-ce-cli containerd.io

# Baixa a versão mais recente do Docker Compose
sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

# Torna o Docker Compose executável
sudo chmod +x /usr/local/bin/docker-compose

# Cria link simbólico para o Docker Compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

echo "Docker e Docker Compose foram instalados com sucesso!"
